- CHANGELOG.md
- android/build.gradle
- android/gradle.properties
- example/android/app/build.gradle
- example/android/build.gradle
- example/android/gradle.properties
- pubspec.yaml
> Complete AndroidX migration

- .github/workflows/publish.yml
Completes #42 (giant PR) by fixing the publisher.
> Publish wakelock 0.2.0 🥳

- .github/workflows/publish.yml
Automates publishing and truly finishes #42 (giant PR) for the v`0.2.0`.
> Automated publishing 🚀

- wakelock_platform_interface/CHANGELOG.md
- wakelock_platform_interface/pubspec.yaml
Fixes the platform interface publish.
> Fix changelog

- .github/workflows/checks.yml
- wakelock_web/CHANGELOG.md
- wakelock_web/pubspec.yaml
Bumps the miminum `import_js_library`.
> Bump import_js_library

- wakelock/CHANGELOG.md
- wakelock/pubspec.yaml
> Fix Android build warning

- .github/workflows/checks.yml
- .github/workflows/publish.yml
*A clear and concise description of what your PR accomplishes.*
> Address env deprecation

- .github/workflows/checks.yml
- .gitignore
- analysis_options.yaml
- wakelock_platform_interface/analysis_options.yaml
- wakelock_platform_interface/lib/method_channel_wakelock.dart
- wakelock_platform_interface/lib/wakelock_platform_interface.dart
- wakelock_platform_interface/pubspec.yaml
- wakelock_platform_interface/test/wakelock_platform_interface_test.dart
Adds null safety to the `wakelock_platform_interface`.
> Platform interface null safety

- wakelock_platform_interface/CHANGELOG.md
- wakelock_platform_interface/pubspec.yaml
The `flutter` SDK constraint prevents null safety Pub badge.
> Remove flutter SDK constraint

- .github/workflows/checks.yml
- wakelock/CHANGELOG.md
- wakelock/example/integration_test/wakelock_test.dart
- wakelock/example/lib/main.dart
- wakelock/example/pubspec.yaml
- wakelock/example/test_driver/integration_test.dart
- wakelock/lib/wakelock.dart
- wakelock/pigeons/messages.dart
- wakelock/pubspec.yaml
- wakelock/test/wakelock_test.dart
- wakelock_web/CHANGELOG.md
- wakelock_web/lib/src/func.dart
- wakelock_web/lib/src/import_js_library.dart
- wakelock_web/lib/src/js_wakelock.dart
- wakelock_web/lib/src/promise.dart
- wakelock_web/lib/wakelock_web.dart
- wakelock_web/pubspec.yaml
Finishes the null safety migration for `wakelock_web` and `wakelock`.
> Migrate to null safety

- .github/workflows/checks.yml
- wakelock/example/pubspec.yaml
- wakelock/ios/Classes/WakelockPlugin.m
[Fix issues 63](https://github.com/creativecreatorormaybenot/wakelock/issues/63#issue-753441324)
User KVO to fix: Avoid changes in `UIApplication.sharedApplication.idleTimerDisabled` unexpected.
> fix: Avoid changes in values unexpected

- wakelock/CHANGELOG.md
- wakelock/pubspec.yaml
> Publish iOS fix

- .github/workflows/licenses.yml
Automatically updates the license files each year and on manual trigger.
> Add license copyright year action

- .github/workflows/licenses.yml
> Adjust license action setup

- LICENSE
Probably a good practice to have that as well.
> Create top-level LICENSE

- LICENSE
- wakelock/LICENSE
- wakelock_platform_interface/LICENSE
- wakelock_web/LICENSE
This reverts commit 3f63f9549b6e564c124611dad12a989e6af7debb.
Want to redo the license commit using commit author.
> Revert "Update copyright year in LICENSE file(s) (#76)"

- .github/workflows/licenses.yml
See https://github.com/FantasticFiasco/action-update-license-year/issues/119.
> Add commit author for license files

- .github/workflows/licenses.yml
See https://github.com/FantasticFiasco/action-update-license-year/issues/119.
> Use custom update license year version

- README.md
- wakelock/CHANGELOG.md
- wakelock/README.md
- wakelock/pubspec.yaml
Adds a table of supported platforms to both the main README and the `wakelock` package README.
> Add supported platforms

- README.md
- analysis_options.yaml
- wakelock/CHANGELOG.md
- wakelock/README.md
- wakelock/ios/wakelock.podspec
- wakelock/lib/wakelock.dart
- wakelock/pubspec.yaml
- wakelock_macos/macos/wakelock_macos.podspec
This PR integrates the `wakelock_windows` implementation created as part of #96 into the `wakelock` package ✨ 
CD will then take care of releasing it 🚀 
cc @Jon-Salmon
> Integrate wakelock_windows into wakelock

- wakelock/CHANGELOG.md
- wakelock/lib/src/windows_stub.dart
- wakelock/lib/wakelock.dart
- wakelock/pubspec.yaml
> Fix broken web builds due to FFI imports

- wakelock/pubspec.yaml
> Publish wakelock

- wakelock/CHANGELOG.md
- wakelock/android/src/main/kotlin/creativemaybeno/wakelock/Wakelock.kt
- wakelock/pubspec.yaml
Removed empty primary constructor
> Remove empty primary constructor

- README.md
- wakelock/CHANGELOG.md
- wakelock/pubspec.yaml
- wakelock_macos/CHANGELOG.md
- wakelock_macos/macos/wakelock_macos.podspec
- wakelock_macos/pubspec.yaml
- wakelock_platform_interface/CHANGELOG.md
- wakelock_platform_interface/pubspec.yaml
- wakelock_web/CHANGELOG.md
- wakelock_web/pubspec.yaml
- wakelock_windows/CHANGELOG.md
- wakelock_windows/pubspec.yaml
This PR replaces the appropriate occurrences of master with main (branches).
> Replace master with main

- .github/workflows/publish.yml
The action does not work right now and we have it in CI anyway.
> Remove pana from CD

- wakelock/pubspec.yaml
- wakelock_macos/pubspec.yaml
- wakelock_platform_interface/pubspec.yaml
- wakelock_web/pubspec.yaml
- wakelock_windows/pubspec.yaml
*A clear and concise description of what your PR accomplishes.*
> Publish all packages

- wakelock_platform_interface/CHANGELOG.md
- wakelock_platform_interface/pubspec.yaml
Bumps the version to prepare to fix #142.
> Upgrade platform interface

- wakelock_macos/CHANGELOG.md
- wakelock_macos/pubspec.yaml
- wakelock_web/CHANGELOG.md
- wakelock_web/pubspec.yaml
- wakelock_windows/CHANGELOG.md
- wakelock_windows/pubspec.yaml
> Bump packages

- wakelock_macos/pubspec.yaml
> Fix macos dependency

- wakelock_macos/CHANGELOG.md
- wakelock_macos/pubspec.yaml
Adds the required CHANGELOG entry.
> Fix macos deployment

- wakelock/CHANGELOG.md
- wakelock/pubspec.yaml
Makes sure that there are no conflicts with old platform interface versions. Fixed #142.
> Fix constraints on updated platform interface

- .github/workflows/checks.yml
- wakelock/CHANGELOG.md
- wakelock/android/build.gradle
- wakelock/android/gradle/wrapper/gradle-wrapper.properties
- wakelock/example/android/app/build.gradle
- wakelock/example/android/app/src/main/AndroidManifest.xml
- wakelock/example/android/app/src/main/kotlin/creativemaybeno/wakelock_example/MainActivity.kt
- wakelock/example/android/build.gradle
- wakelock/example/android/gradle/wrapper/gradle-wrapper.properties
- wakelock/pubspec.yaml
> Upgrade Android embedding

- .github/workflows/checks.yml
Fixes the lack of `xcrun instruments` with Xcode 13.
> Fix iOS integration tests

- wakelock/CHANGELOG.md
- wakelock/pubspec.yaml
> Release 0.6.1

- wakelock/CHANGELOG.md
- wakelock/README.md
- wakelock/pubspec.yaml
> Document how to use wakelock in `main`

- .github/workflows/checks.yml
- wakelock/example/android/app/src/main/AndroidManifest.xml
*A clear and concise description of what your PR accomplishes.*
> omiting "io.flutter.embedding.android.SplashScreenDrawable"
